version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: messaging_db
    environment:
      POSTGRES_USER: minh271003
      POSTGRES_PASSWORD: minh210513
      POSTGRES_DB: messaging
    ports:
      - '5422:5422'
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: messaging_app
    ports:
      - '8000:8000'
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://minh271003:minh210513@db:5432/messaging
      PORT: 8000

volumes:
  db_data:
