version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: messaging_db
    restart: always
    environment:
      POSTGRES_USER: minh271003
      POSTGRES_PASSWORD: minh210513
      POSTGRES_DB: messaging
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
